import { SyllabusChapter, FormulaItem, Flashcard } from "./types";

export const NEET_SYLLABUS_TEMPLATE: SyllabusChapter[] = [
  // --- BIOLOGY ---
  {
    id: "bio-01",
    subject: "Biology",
    name: "Cell: The Unit of Life",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 2,
    notesReviewed: true,
    formulaRevised: false,
    questionPracticeCount: 80,
    pyqsDone: true,
    mockTested: true,
    masteryStatus: "mastered",
  },
  {
    id: "bio-02",
    subject: "Biology",
    name: "Genetics: Principles of Inheritance",
    classGrade: 12,
    theoryDone: false,
    ncertReadCount: 0,
    notesReviewed: false,
    formulaRevised: false,
    questionPracticeCount: 0,
    pyqsDone: false,
    mockTested: false,
    masteryStatus: "not_started",
  },
  {
    id: "bio-03",
    subject: "Biology",
    name: "Human Physiology: Chemical Coordination",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 1,
    notesReviewed: false,
    formulaRevised: false,
    questionPracticeCount: 12,
    pyqsDone: false,
    mockTested: false,
    masteryStatus: "weak",
  },
  {
    id: "bio-04",
    subject: "Biology",
    name: "Plant Physiology: Photosynthesis",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 1,
    notesReviewed: true,
    formulaRevised: false,
    questionPracticeCount: 40,
    pyqsDone: true,
    mockTested: false,
    masteryStatus: "revision_due",
  },
  {
    id: "bio-05",
    subject: "Biology",
    name: "Ecology: Biodiversity and Conservation",
    classGrade: 12,
    theoryDone: false,
    ncertReadCount: 0,
    notesReviewed: false,
    formulaRevised: false,
    questionPracticeCount: 0,
    pyqsDone: false,
    mockTested: false,
    masteryStatus: "not_started",
  },

  // --- PHYSICS ---
  {
    id: "phy-01",
    subject: "Physics",
    name: "Units, Dimensions & Errors",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 1,
    notesReviewed: true,
    formulaRevised: true,
    questionPracticeCount: 95,
    pyqsDone: true,
    mockTested: true,
    masteryStatus: "mastered",
  },
  {
    id: "phy-02",
    subject: "Physics",
    name: "Kinematics: Motion in a Straight Line",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 1,
    notesReviewed: true,
    formulaRevised: true,
    questionPracticeCount: 30,
    pyqsDone: true,
    mockTested: false,
    masteryStatus: "revision_due",
  },
  {
    id: "phy-03",
    subject: "Physics",
    name: "Laws of Motion",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 0,
    notesReviewed: false,
    formulaRevised: false,
    questionPracticeCount: 8,
    pyqsDone: false,
    mockTested: false,
    masteryStatus: "weak",
  },
  {
    id: "phy-04",
    subject: "Physics",
    name: "Electrostatics: Charges and Fields",
    classGrade: 12,
    theoryDone: false,
    ncertReadCount: 0,
    notesReviewed: false,
    formulaRevised: false,
    questionPracticeCount: 0,
    pyqsDone: false,
    mockTested: false,
    masteryStatus: "not_started",
  },
  {
    id: "phy-05",
    subject: "Physics",
    name: "Current Electricity",
    classGrade: 12,
    theoryDone: false,
    ncertReadCount: 0,
    notesReviewed: false,
    formulaRevised: false,
    questionPracticeCount: 0,
    pyqsDone: false,
    mockTested: false,
    masteryStatus: "not_started",
  },

  // --- CHEMISTRY ---
  {
    id: "chem-01",
    subject: "Chemistry",
    name: "Some Basic Concepts of Chemistry (Mole Concept)",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 1,
    notesReviewed: true,
    formulaRevised: true,
    questionPracticeCount: 110,
    pyqsDone: true,
    mockTested: true,
    masteryStatus: "mastered",
  },
  {
    id: "chem-02",
    subject: "Chemistry",
    name: "Chemical Bonding and Molecular Structure",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 0,
    notesReviewed: true,
    formulaRevised: false,
    questionPracticeCount: 25,
    pyqsDone: true,
    mockTested: false,
    masteryStatus: "revision_due",
  },
  {
    id: "chem-03",
    subject: "Chemistry",
    name: "Coordination Compounds",
    classGrade: 12,
    theoryDone: true,
    ncertReadCount: 1,
    notesReviewed: true,
    formulaRevised: false,
    questionPracticeCount: 50,
    pyqsDone: true,
    mockTested: false,
    masteryStatus: "mastered",
  },
  {
    id: "chem-04",
    subject: "Chemistry",
    name: "Organic Chemistry: GOC & Hydrocarbons",
    classGrade: 11,
    theoryDone: true,
    ncertReadCount: 0,
    notesReviewed: false,
    formulaRevised: false,
    questionPracticeCount: 5,
    pyqsDone: false,
    mockTested: false,
    masteryStatus: "weak",
  },
];

export const FORMULAS_TEMPLATE: FormulaItem[] = [
  {
    id: "f-01",
    subject: "Physics",
    chapterId: "phy-01",
    chapterName: "Units, Dimensions & Errors",
    title: "Propagation of Relative Error (Multiplication)",
    formula: "ΔZ / Z = ± ( ΔA / A + ΔB / B )",
    description: "Used to determine the maximum fractional uncertainty of composite measured quantities when they are multiplied or divided.",
    isBookmarked: false,
  },
  {
    id: "f-02",
    subject: "Physics",
    chapterId: "phy-03",
    chapterName: "Laws of Motion",
    title: "Maximum Velocity on a Banked Road",
    formula: "v_max = √[ g * r * (μ + tanθ) / (1 - μ*tanθ) ]",
    description: "Optimum safe speed of an automobile rounding a banked circular turn under frictional road coefficient μ.",
    isBookmarked: true,
  },
  {
    id: "f-03",
    subject: "Chemistry",
    chapterId: "chem-01",
    chapterName: "Some Basic Concepts of Chemistry (Mole)",
    title: "Molarity of a Solution",
    formula: "M = [ Weight of Solute (g) * 1000 ] / [ Molar Mass * Vol of Solution (mL) ]",
    description: "Specifies molar concentration density, expressed as the number of moles of solute per liter of composite solution.",
    isBookmarked: false,
  },
  {
    id: "f-04",
    subject: "Chemistry",
    chapterId: "chem-02",
    chapterName: "Chemical Bonding",
    title: "Bond Order Formula",
    formula: "Bond Order = 0.5 * ( N_b - N_a )",
    description: "Determined from Molecular Orbital theory, where Nb represents bonding molecular orbital electrons and Na is antibonding.",
    isBookmarked: false,
  },
];

export const FLASHCARDS_TEMPLATE: Flashcard[] = [
  {
    id: "fc-01",
    subject: "Biology",
    chapterId: "bio-01",
    chapterName: "Cell: The Unit of Life",
    question: "What is the primary carbohydrate constituent of fungal cell walls?",
    answer: "Chitin, which is a structural polymer of N-acetylglucosamine (NAG) linked together by β-1,4-glycosidic bonds.",
    box: 3,
    nextReviewDate: new Date().toISOString().split("T")[0],
  },
  {
    id: "fc-02",
    subject: "Biology",
    chapterId: "bio-03",
    chapterName: "Chemical Coordination",
    question: "Which specific endocrine hormone triggers the sharp LH surge causing ovulation?",
    answer: "A sustained high feedback surge of Estrogen (specifically estradiol) from the ripening Graafian follicle around day 12-13 of the cycle.",
    box: 1,
    nextReviewDate: new Date().toISOString().split("T")[0],
  },
  {
    id: "fc-03",
    subject: "Physics",
    chapterId: "phy-03",
    chapterName: "Laws of Motion",
    question: "Why is the coefficient of static friction (μs) always greater than kinetic friction (μk)?",
    answer: "At rest, surface irregularities have ample time to interlock microscopically. Once relative motion begins, the contact points slide over each other without locking fully.",
    box: 2,
    nextReviewDate: new Date().toISOString().split("T")[0],
  },
];
